drop table if exists lecture CASCADE;
create table lecture (
  id bigint generated by default as identity,
  name varchar(255),
  start_time DATETIME
);

insert into lecture (name, start_time) values ( 'A', '2024-03-25' );
insert into lecture (name, start_time) values ( 'B', '2024-03-26' );
insert into lecture (name, start_time) values ( 'C', '2024-03-27' );


drop table if exists member CASCADE;
create table member (
    id bigint generated by default as identity
    name varchar(255)
);



insert into member (id) values (1);
insert into member (id) values (2);
insert into member (id) values (3);
